### ISSUE TITLE
Blank website

### ISSUE THREAD

**Issue by dr-apple** [deskmatik/deskmatik#2]
Hello, i have flash a esp8266 with your firmware,....

I Conncet my Mac / iPhone / PC to the SSID DESKMATIC with 123456789 and go with all browsers Chrome, Firefox, Safari to http://192.168.4.1/settings, but it come a blank site :-(

**Comment by duramson** [comment]
Same Issue. Flashed a Wemos D1 mini and also got a blank page.

**Comment by uxigene** [comment]
@dr-apple @duramson could you please try to access the webpage in chrome on PC? A screenshot of devconsole would help.

**Comment by uxigene** [comment]
@dr-apple @duramson Also there is an important step which I forgot to mention in the readme. Have you uploaded the files from "data" directory to SPIFFS? Here is an example how to do that. https://www.instructables.com/Using-ESP8266-SPIFFS/

**Comment by duramson** [comment]
Ohh yes, that was the point. You should look into PlatformIO to make the Process easier https://docs.platformio.org/en/latest/platforms/espressif8266.html#using-filesystem or you can provide an upload-interface like ESP3D https://github.com/luc-github/ESP3D

**Comment by uxigene** [comment]
@duramson Thanks, I'll take a look on platformio. Can I close the issue?

**Comment by uxigene** [comment]
@dr-apple @duramson please note that there is Desktop app in development https://github.com/deskmatik/deskmatik/issues/1 You can find zip archive and try it (there is link in the comments).
